apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: testing
resources:
- ../../base
- namespace.yaml
patches:
- path: deployment-patch.yaml
  target:
    kind: Deployment
    name: flask-app-deployment
- path: service-patch.yaml
  target:
    kind: Service
    name: flask-app-service
