apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  labels:
    env: testing # Environment label for the Service
spec:
  type: LoadBalancer # for external IP
  selector:
    app: flask-app
    env: testing # Selector to match pods with these labels
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  - protocol: TCP
    port: 443
    targetPort: 5000
