apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
  labels:
    env: staging
spec:
  template:
    metadata:
      labels:
        app: flask-app
        env: staging
    spec:
      containers:
      - name: flask-app-container
        image: edunseng/my-flask-webapp:1.0
        env:  # Define environment variables here
        - name: staging
          value: "staging"
