apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  labels:
    env: staging  # Environment label for the Service
spec:
  selector:
    app: flask-app
    env: staging  # Selector to match pods with these labels
