# .github/workflows/docker-build-push-deploy.yml
name: Docker Build-Push - main

on:
  push:
    paths:
      - 'src/**' # Trigger only when src/ changes
    branches: [ main ]
    tags: [ 'v*.*.*' ]
  workflow_dispatch: # ✅ Enables manual triggering

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Full Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Ensure full repository is cloned

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Determine Version Tag
      id: version
      # Docker tags align with Git tags:  v1.2.3 -> 1.2.3 & feature/new-ui -> feature-new-ui
      run: |
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          VERSION="${GITHUB_REF#refs/tags/}"
          SANITIZED_VERSION="${VERSION//v/}"          # Remove "v"
          SANITIZED_VERSION="${SANITIZED_VERSION//\//-}"  # Replace "/" with "-"
          echo "TAG_VERSION=$SANITIZED_VERSION" >> $GITHUB_ENV
        else
          echo "TAG_VERSION=latest" >> $GITHUB_ENV
        fi

    #- name: Debug - List workspace contents
    #  run: |
    #    echo "Current workspace: ${{ github.workspace }}"
    #    ls -la ${{ github.workspace }}
#
    #- name: Debug - Check permissions for all files
    #  run: |
    #    ls -lR ${{ github.workspace }}
    #    
    #- name: Debug - Show environment variables
    #  run: env
#
    #- name: Debug - Check if src exists
    #  run: |
    #    if [ -d "${{ github.workspace }}/src" ]; then
    #      echo "✅ src directory found!"
    #      ls -la ${{ github.workspace }}/src
    #    else
    #      echo "❌ src directory is MISSING!"
    #    fi
#
    - name: Install Ansible
      run: |
        sudo apt update
        sudo apt install -y ansible

    - name: Set HOME to GitHub Workspace
      run: |
        echo "HOME=${{ github.workspace }}" >> $GITHUB_ENV

        
    - name: Run Ansible Playbook
      run: |
        cd ${{ github.workspace }}  # Ensure we're in the right directory
        ansible-playbook -i localhost, ansible/playbooks/build/docker-build-push.yml -e "build_path=src/"
        
      env:
        VERSION_TAG: ${{ env.TAG_VERSION }}  # Pass the sanitized tag
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

